name: Deploy Storybook to GitHub Pages

on:
    push:
        branches:
          - '**'
env:
    DEFAULT_NODE_VERSION: '16'
    WORKSPACE_COMMAND_PREFIX: 'pnpm -F @hub/hds'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version:  ${{ env.DEFAULT_NODE_VERSION }}

      - name: Install pnpm
        run: npm install -g pnpm
  
      - name: Install dependencies
        run: pnpm install

      - name: Build Storybook
        run: ${{ env.WORKSPACE_COMMAND_PREFIX }} run build-storybook

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./storybook-static
